export { default as Nav } from "./Nav.jsx";
export { default as Hero } from "./Hero.jsx";
export { default as CallToAction } from "./CallToAction.jsx";
export { default as ChooseUs } from "./ChooseUs.jsx";
export { default as WhatWeDo } from "./WhatWeDo.jsx";
export { default as Technologies } from "./Technologies.jsx";
export { default as Stages } from "./Stages.jsx";
export { default as Contact } from "./Contact.jsx";
export { default as Footer } from "./Footer.jsx";
